services:
  db:
    image: postgres:15
    container_name: scraper_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dumps:/app/dumps
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s

  scraper:
    build: .
    container_name: python_scraper
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./dumps:/app/dumps
    command: python main.py

  scheduler:
    build: .
    container_name: python_scheduler
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./dumps:/app/dumps
    command: python scheduler.py

volumes:
  db_data: